#!/usr/bin/env python3
"""Build a separate, source-asset PH2 Spectrum sprite laboratory snapshot.

The original game art is intentionally an external input.  Point
PH2_ASSET_DIR at a checked-out source atlas; generated image/inc files and the
SNA remain ignored build products.
"""
from __future__ import annotations

import hashlib
import json
import os
import shutil
import struct
import subprocess
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
OUT = HERE / "artifacts"
ATLAS_ROOT = Path(os.environ.get("PH2_ASSET_DIR", "/tmp/ph2-phaser"))
ATLAS_PATH = ATLAS_ROOT / "assets/spritesheets/pre2atlas.png"
ATLAS_JSON = ATLAS_ROOT / "assets/spritesheets/pre2atlas.json"
TILESET_PATH = ATLAS_ROOT / "assets/tilesets/L1.png"
BANK, SNA_SIZE = 0x4000, 131_103
PLAYER_X, PLAYER_Y = 112, 80
PLAYER_W, PLAYER_H = 32, 40


def zx_address(y: int) -> int:
    return 0x4000 + ((y & 0xC0) << 5) + ((y & 7) << 8) + ((y & 0x38) << 2)


def require_sources() -> None:
    missing = [str(path) for path in (ATLAS_PATH, ATLAS_JSON, TILESET_PATH) if not path.exists()]
    if missing:
        raise RuntimeError("PH2 source atlas is required; set PH2_ASSET_DIR. Missing: " + ", ".join(missing))


def frame(atlas: Image.Image, atlas_json: dict, key: str) -> Image.Image:
    spec = atlas_json["frames"][key]["frame"]
    return atlas.crop((spec["x"], spec["y"], spec["x"] + spec["w"], spec["y"] + spec["h"]))


def mono_values(image: Image.Image) -> tuple[list[int], list[int]]:
    """Return opaque mask and ordered-dithered white ink pixels."""
    rgba = image.convert("RGBA")
    opaque, ink = [], []
    bayer = ((0, 8, 2, 10), (12, 4, 14, 6), (3, 11, 1, 9), (15, 7, 13, 5))
    for y in range(rgba.height):
        for x in range(rgba.width):
            r, g, b, a = rgba.getpixel((x, y))
            solid = a >= 32
            # The maximum channel keeps the original saturated jungle greens
            # legible after the forced monochrome reduction.
            light = max(r, g, b) * 0.58 + (r * 0.2126 + g * 0.7152 + b * 0.0722) * 0.42
            threshold = (bayer[y & 3][x & 3] + 0.5) * 16
            opaque.append(int(solid))
            ink.append(int(solid and light >= threshold))
    return opaque, ink


def stamp(canvas: Image.Image, sprite: Image.Image, x: int, y: int) -> None:
    """Stamp source art over the black laboratory scene, preserving alpha."""
    rgba = canvas.convert("RGBA")
    rgba.alpha_composite(sprite, (x, y))
    canvas.paste(rgba.convert("RGB"))


def build_scene(atlas: Image.Image, atlas_json: dict, tileset: Image.Image) -> Image.Image:
    canvas = Image.new("RGB", (256, 192), (0, 0, 0))
    # Authentic level-one rock/foliage pieces form the ground, rather than a
    # hand-drawn substitute.  The copies overlap as they would in a tile map.
    ground = tileset.crop((0, 288, 176, 384))
    stamp(canvas, ground, -14, 120)
    stamp(canvas, ground, 140, 120)
    stamp(canvas, tileset.crop((0, 208, 96, 286)), 72, 134)
    # Atlas 420/433 are authored PH2 foliage; 308 is its level portal/checkpoint.
    stamp(canvas, frame(atlas, atlas_json, "420"), 18, 124)
    stamp(canvas, frame(atlas, atlas_json, "433"), 50, 130)
    stamp(canvas, frame(atlas, atlas_json, "308"), 194, 80)
    return canvas


def bitmap_from_image(image: Image.Image) -> bytes:
    opaque, ink = mono_values(image)
    result = bytearray(6144)
    for y in range(192):
        base = zx_address(y) - 0x4000
        for xbyte in range(32):
            value = 0
            for bit in range(8):
                value = (value << 1) | ink[y * 256 + xbyte * 8 + bit]
            result[base + xbyte] = value
    return bytes(result)


def player_canvas(atlas: Image.Image, atlas_json: dict, key: str) -> Image.Image:
    source = frame(atlas, atlas_json, key)
    result = Image.new("RGBA", (PLAYER_W, PLAYER_H), (0, 0, 0, 0))
    result.alpha_composite(source, ((PLAYER_W - source.width) // 2, PLAYER_H - source.height))
    return result


def write_generated(atlas: Image.Image, atlas_json: dict, scene: Image.Image) -> None:
    (HERE / "generated_asset_lab_background.bin").write_bytes(bitmap_from_image(scene))
    rows = ["; Generated by build_asset_lab.py from the configured PH2 source atlas.", "SPRITE_ROWS_SOURCE:"]
    for y in range(PLAYER_H):
        rows.append(f"        DW 0x{zx_address(PLAYER_Y + y) + 0x6000 + PLAYER_X // 8:04X}")
    rows.append("SPRITE_ROWS_5:")
    for y in range(PLAYER_H):
        rows.append(f"        DW 0x{zx_address(PLAYER_Y + y) + PLAYER_X // 8:04X}")
    rows.append("SPRITE_ROWS_7:")
    for y in range(PLAYER_H):
        rows.append(f"        DW 0x{0xC000 + zx_address(PLAYER_Y + y) - 0x4000 + PLAYER_X // 8:04X}")

    keys = ("25", "27", "30", "35", "36")  # Original man idle sequence.
    rows += ["SPRITE_FRAME_TABLE:"] + [f"        DW SPRITE_FRAME{i}" for i in range(len(keys))]
    for frame_index, key in enumerate(keys):
        opaque, ink = mono_values(player_canvas(atlas, atlas_json, key))
        rows.append(f"SPRITE_FRAME{frame_index}:")
        for y in range(PLAYER_H):
            values = []
            for byte in range(PLAYER_W // 8):
                mask, data = 0, 0
                for bit in range(8):
                    pixel = y * PLAYER_W + byte * 8 + bit
                    mask = (mask << 1) | (opaque[pixel] ^ 1)
                    data = (data << 1) | ink[pixel]
                values.extend((mask, data))
            rows.append("        DB " + ", ".join(f"0x{value:02X}" for value in values))
    (HERE / "generated_asset_lab.inc").write_text("\n".join(rows) + "\n", encoding="ascii")


def assemble() -> bytes:
    assembler = os.environ.get("SJASMPLUS") or shutil.which("sjasmplus")
    if not assembler:
        raise RuntimeError("sjasmplus is required; set SJASMPLUS to its executable path")
    binary = OUT / "ph2-asset-lab-code.bin"
    result = subprocess.run([assembler, f"--raw={binary}", "ph2_asset_lab.asm"], cwd=HERE, text=True, capture_output=True)
    if result.returncode:
        raise RuntimeError(f"sjasmplus failed\n{result.stdout}\n{result.stderr}")
    return binary.read_bytes()


def make_sna(code: bytes, background: bytes) -> bytes:
    pages = [bytearray(BANK) for _ in range(8)]
    pages[2][:len(code)] = code
    for bank in (5, 7):
        pages[bank][:6144] = background
        pages[bank][6144:6912] = bytes([0x47]) * 768
    header = bytearray(27)
    header[19], header[23:25], header[25] = 4, struct.pack("<H", 0xBFF0), 1
    blob = bytearray(header) + pages[5] + pages[2] + pages[0] + struct.pack("<HBB", 0x8000, 0, 0)
    for bank in (1, 3, 4, 6, 7):
        blob += pages[bank]
    if len(blob) != SNA_SIZE:
        raise AssertionError(len(blob))
    return bytes(blob)


def main() -> None:
    require_sources()
    OUT.mkdir(exist_ok=True)
    atlas = Image.open(ATLAS_PATH).convert("RGBA")
    atlas_json = json.loads(ATLAS_JSON.read_text(encoding="utf-8"))
    scene = build_scene(atlas, atlas_json, Image.open(TILESET_PATH).convert("RGBA"))
    scene.save(OUT / "prehistorik2-cpc-asset-sprite-lab-source.png")
    write_generated(atlas, atlas_json, scene)
    code = assemble()
    background = (HERE / "generated_asset_lab_background.bin").read_bytes()
    snapshot = make_sna(code, background)
    sna = OUT / "prehistorik2-cpc-asset-sprite-lab.sna"
    sna.write_bytes(snapshot)
    manifest = {"target": "Stock ZX Spectrum 128K PAL", "source_assets": {"atlas_frames": {"player_idle": [25, 27, 30, 35, 36], "bushes": [420, 433], "checkpoint": 308}, "reduction": "alpha mask + ordered monochrome dither"}, "compositor": {"formula": "(destination AND mask) OR ink", "sprite": "32x40", "background_restore": "4 bytes x 40 rows", "attributes": "fixed bright white ink on black paper"}, "snapshot": {"bytes": len(snapshot), "sha256": hashlib.sha256(snapshot).hexdigest()}}
    (OUT / "asset-lab-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
